kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ${{values.component_id}}
  namespace: ${{values.component_id}}-dev
spec:
  host: ${{values.component_id}}-${{values.component_id}}-dev.apps.cluster-zj2wm.zj2wm.sandbox2740.opentlc.com
  path: /
  to:
    kind: Service
    name: ${{values.component_id}}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
